# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

answer = 0

def fib_seq(top_val):
    fib = [1,2]

    while fib[-1] < top_val:
        fib.append(fib[-2]+fib[-1])
    fib = fib[:-1]

    return(fib)

f = fib_seq(4000000)

for i in f:
    if i % 2 == 0:
        answer = answer + i

print(answer)